# -*- coding: utf-8 -*-
"""warn

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K-zEmvSUOpXQ20wcpiS6eOpcw88U8-fd
"""

import turtle

n = int(input("Please input a number between 100 - 300 : "))

t = turtle.Turtle()

t.penup()
t.goto(-110,-110)
t.pendown()
t.pensize(n//10)
t.pencolor("black")

# t.speed(50)
t.fillcolor("yellow")
t.begin_fill()
for i in range(3):
    t.forward(n)
    t.left(120)
t.end_fill()

t.penup()

t.speed(50)
t.pencolor("black")
middle = int(n // 2)
t.goto(middle-110,middle-110)
t.pendown()
t.right(90)
length = n//4
while(length):
  t.pensize(length//2)
  t.forward(1)
  length -= 1
t.penup()
space = n//10
t.forward(space)
t.pendown()
t.pensize(n//10)
t.forward(2)


t.hideturtle()
turtle.done()#!/bin/python3
