# -*- coding: utf-8 -*-
"""timetest

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bQh-fLMBnWP1weQWDMGnYa74W75WObdH
"""

import time 

def fib(n):

  start = time.time()
  if n == 1 or n == 2:
    return 1
  else:
    return fib(n-1)+fib(n-2)

for i in range (1,35):
  start = time.time()
  ans = fib(i)
  end = time.time()
  print("For number %d , the fibonacci number is %d and the time required is %10.7f seconds" %(i, ans, end-start))



