# -*- coding: utf-8 -*-
"""1001

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s9z29dOh_-UlO7QaFPVtB6pLK039SEg5
"""

num1 = int(input())
num2 = int(input())
print(num1+num2)
