# -*- coding: utf-8 -*-
"""1002

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_AGqIbDJXV8CFC3wSAjwwCienMFcf3n2
"""

a = input()
b = ''.join(reversed(a))
print(b)

