# -*- coding: utf-8 -*-
"""1003

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2euLH0pmKlp1tNl3H9lq3CzHB99CVrm
"""

pi = 3.14159
r = int(input())
circumference = 2*pi*r
area = pi*(r**2)

print(round(circumference,4), end=' ')
print(round(area,4))

