# -*- coding: utf-8 -*-
"""1004

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C43noqHLGBM05OQulqbGsj1AffrBE44K
"""

r = eval(input())
if r <= 0:
  print(0)
else:
  pi = 3.14
  volume = ((4.0/3.0)*pi*(r**3))
  print(round(volume,2))

