# -*- coding: utf-8 -*-
"""1005

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fDJTgxif-fn9Frr3k6TGWIsQRzbjVyTa
"""

resistance1 = eval(input())
resistance2 = eval(input())
total_resistance = 1/(1/resistance1 + 1/resistance2)
print(round(total_resistance,2))

