# -*- coding: utf-8 -*-
"""1006

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nFR5G6LE-UjQs6Wu88aOJEIT2hrvoL2c
"""

a1 = eval(input())
a2 = eval(input())
n = eval(input())
diff = a2-a1
ans = a1 + (n-1)*diff
print(ans)

