# -*- coding: utf-8 -*-
"""1007

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDO9VnsmFupP81ZlTG6dQ42bcUSvcQt7
"""

a = eval(input())
b = eval(input())
ans = a/b
print(round(ans,9))

