# -*- coding: utf-8 -*-
"""1008

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZEReA7GSTz5URxQhs_XAhAUuqQl455Ry
"""

a = eval(input())
b = eval(input())
c = eval(input())
mean = (a+b+c)/3
print(round(mean,2))

