# -*- coding: utf-8 -*-
"""1009

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kCG780_LyubXYrmexrH52caGyRD-0PS7
"""

a = int(input())
b = int(input())
ans1 = a//b
ans2 = a%b
print(ans1, end=' ')
print(ans2)

