# -*- coding: utf-8 -*-
"""1010

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WZc3QmK7E1y-2phNu0kOjXfReWq-JjiC
"""

n = int(input())
x = int(input())
y = int(input())

temp = (y//x)
if((temp*x)<y):
  temp+=1

ans = n - temp

if(ans>=0):
  print(ans)

else:
  print(0)

