# -*- coding: utf-8 -*-
"""func

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E-al5ghE2wPnJty_yRGve4H2IrwRcha-
"""

# func.py
x = float(input("Please input x:"))
a = 2
b = -45
c = 13
y = a * x ** 2 + b * x + c
print('x =', x)
print('y =', y)

# x=0, y=13
# x=10, y=-237
# x=-30, y=3163

