# -*- coding: utf-8 -*-
"""1101

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MXuEmZ-gPnwacHaQfGrPIu71BVNZK7nP
"""

n = int(input())
for i in range (n):
  for j in range(n):
    print("*",end ='')
  print()
