# -*- coding: utf-8 -*-
"""1002

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SzDzUYCypfU24F6mypit48kfTFK6nXu6
"""

n = int(input())
cnt = 1

for i in range(n):
  for j in range(cnt):
    print("*",end = '')
  cnt += 1
  print()

