# -*- coding: utf-8 -*-
"""1103

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XWVO9PTZBYBsVFWnDQZXROSkWNvu-yGu
"""

n = int(input())
ans = 1

for i in range(1,n+1):
  ans*= i

print(ans)

