# -*- coding: utf-8 -*-
"""1104

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-6_OX3YuxASHGBWbQsTasEzEnh4Cfkbl
"""

n = int(input())
ans = 0

for i in range(0,n+1):
  if ((i%7==0) or ('7'in str(i))):
    continue
  else:
    ans+=i

print(ans)

