# -*- coding: utf-8 -*-
"""1406

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Eq-aAiK48Q2PE0T4MyNohPKvq9p_ky2h
"""

n = int(input())
cnt = 0

for i in range(1,n+1):
  temp = i
  while(temp>=1):
    val = temp%10
    if(str(val) == '1'):
      cnt+=1
    temp = temp//10


print(cnt)

