# -*- coding: utf-8 -*-
"""1704

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WceogDCqpgyBuVkBBj--KrnzgydogbI1
"""

import math
n = int(input())
prime = True
temp = math.sqrt(n)
temp = int(temp)

if n == 3 or n == 2:
  print("yes")

elif n == 1:
  print("no")

else:
  for i in range(2,temp+1):
    if(n%i==0):
      prime=False
      break

  if prime==False:
    print("no")

  elif prime == True:
    print("yes")

