# -*- coding: utf-8 -*-
"""1714

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QmyeEguzNYrKaqVaqSqKhi5DR6XIc9TQ
"""

import math
a = int(input())
b = int(input())
cnt = 0



for i in range(a,b+1):
  temp = math.sqrt(i)
  temp = int(temp)
  # print(temp,end=' ')
  prime = True
  for j in range(2,temp+1):
    if(i%j==0):
      prime = False
      # print(f"{i}%{j}")
      break
  if prime == True:
    # print(i)
    cnt+=1
     

print(cnt)

