# -*- coding: utf-8 -*-
"""treeart

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhQ5oz1lFh-EXdk_2lbfVrvQlE8uofc7
"""

import turtle
import random


t = turtle.Screen()
t.setworldcoordinates(-700,-700,700,700)
#t.setworldcoordinates(-1700,-1700,1700,1700)
t.bgcolor("aquamarine")

t = turtle.Turtle()

flower_color = ['salmon','tomato','navajo white','orange red','coral','dark salmon','gold','orange']
branch_color = ['dark goldenrod','sienna','saddle brown',]

turtle.tracer(0,0)
def tree(branch_len):
  if branch_len >5:    
    b_c = random.choice(branch_color)
    t.pencolor(b_c)
    t.pensize(branch_len/7)
    t.forward(branch_len - 3)
    t.pensize((branch_len/7)-1)
    t.forward(3)
    t.right(20)
    
    # f_c = random.choice(flower_color)
    # t.pencolor(f_c)
    # t.dot(10)
    n = random.randint(8,15)
    tree(branch_len - n)
    
    t.left(40)
    
    f_c = random.choice(flower_color)
    t.pencolor(f_c)
    t.dot(10)
    
    n = random.randint(8,15)
    tree(branch_len - n)
    
    t.right(20)
    
    # f_c = random.choice(flower_color)
    # t.pencolor(f_c)
    # t.dot(10)
    
    t.pencolor(b_c)
    t.backward(branch_len)

t.left(90)
t.penup()
t.pensize(15)
t.backward(450)
t.pendown()
t.pencolor('peru')
# t.pensize(2)
# t.pencolor('black')
# t.dot(10)
tree(130)

t.hideturtle()
turtle.update()
turtle.done()